### PR TITLE
Remove IteratorInterfaceExtensions @require clause

### PR DESCRIPTION
**Pull request by davidanthoff**
I think this is a better fix than https://github.com/JuliaData/Tables.jl/pull/71.

CC @nalimilan

### CODE REVIEW

**Comment by nalimilan** [comment]
Hmm, so we actually depend on IteratorInterfaceExtensions? Then why was it using `@require`?

**Comment by davidanthoff** [comment]
Yes, and I have no idea.

**Comment by davidanthoff** [comment]
@quinnj Bump, any reason not to merge this?

**Review by quinnj — APPROVED** [review]
Thanks!

**Pull request merged**
