### PR TITLE
Finixh #58 by adding the vardim keyword argument to Tables.matrix, al…

### PR DESCRIPTION
**Pull request by quinnj**
…lowing the user to specify whether input columns should be materialized as matrix columns or rows

### CODE REVIEW

**Comment by nalimilan** [comment]
Thanks, looks good! My only hesitation is whether we should call the keyword argument `vardim`. The only place where that term is used currently AFAIK is in StatsBase's weighted `cov`, but it's going to be changed to `dims` for consistency with `Statistics.cov`. That said, `vardim` sounds clearer (`dims` would look weird here) and it could be used for https://github.com/JuliaStats/Clustering.jl/issues/79.

**Comment by andreasnoack** [comment]
I think `dims` and `vardim` are equally confusing but since the reductions in Base use `dims`, we have been switching from `vardim` to `dims` in `StatsBase` (although the switch is not yet complete) so I think it would better to use `dims` because of the precedence.

**Comment by quinnj** [comment]
Updated from `vardim` to `dims`.

**Comment by nalimilan** [comment]
That naming issue is quite annoying. After thinking more about it, I feel like using `dims=1` to mean "transform columns to rows" is quite arbitrary. We could as well say `dims=2` means "transform rows to columns", or any other intepretation. There's actually no clear relationship with reductions which use the `dims` argument in Base.

Maybe `transpose::Bool=false` would be clearer? `CSV.file` already supports that argument.

**Comment by quinnj** [comment]
So what should we do here? I don't have strong opinions.

**Comment by nalimilan** [comment]
I think I prefer `transpose`.

**Comment by tlienart** [comment]
I think `transpose` makes sense here. at the end of the day if this is well documented, it should be fine.

**Pull request merged**
