### PR TITLE
Inline of `replacex` in `add_or_widen!` (compilation performance) and use of `OrderedDict` in `dictcolumntable` (column ordering)

### PR DESCRIPTION
**Pull request by mathieu17g**
In case the propositions made in https://github.com/JuliaData/Tables.jl/issues/273#issuecomment-1037986769 and https://github.com/JuliaData/Tables.jl/issues/274#issue-1145052654 are accepted, this PR can solve issues #273 and #274

### CODE REVIEW

**Comment by bkamins** [comment]
Looks good, but @quinnj knows the details.

**Comment by bkamins** [comment]
@quinnj - could you have a look at this PR please?

**Review by quinnj — APPROVED** [review]
Hmmmm, yes, I guess this is all fine. The inline of `replacex` is obviously fine; for the `OrderedDict` change, I would note that we've typically directed users to only rely on the column ordering provided by the _schema_ instead of any "default" table order. Though in the dict case I can see how using an OrderedDict would be quite useful/convenient and so I'm in favor.

It does make me wonder if we should clarify in the docs about this: should table formats be _required_ to store columns in a specific order? We don't currently because the interface already exposes `getcolumn(cols, i)`, so that _feels_ like you're getting the columns in order.

**Comment by bkamins** [comment]
Given we say that:

> The methods taking a single `Symbol` or `Int` are both required for the `AbstractColumns` and `AbstractRow` interfaces

I think we should require that the order is somehow guaranteed. In other words - since we allow getting column by integer it would be good to clarify what this means in general (not only by default - which is defined to use `getfield`).

**Pull request merged**
