### PR TITLE
`OrderedDict` for `dictrowtable`

### LINKED ISSUE #274: Make Tables.dictrowtable use OrderedDict
It is debatable, but maybe it is better for `Tables.dictrowtable` to preserve the order of appearance of columns in the input by switching it to use `OrderedDict` internally?

### PR DESCRIPTION
**Pull request by mathieu17g**
Fixes #274

`OrderedDict` for `dictrowtable`

### CODE REVIEW

**Comment by bkamins** [comment]
Also docstrings for `dictcoltable` and `dictrowtable` require fixing.

**Comment by mathieu17g** [comment]
Oups sorry, I was a bit sloppy...

**Comment by mathieu17g** [comment]
Independently of this PR, something is going wrong with julia nightly on `size(::GenericColumn{Int64})` not implemented on `GenericColumn` test helper structure

**Comment by mathieu17g** [comment]
Nightly build seems to have regressions (seen on other package CI). I have reverted to test introduced in commit [9b91dff](https://github.com/JuliaData/Tables.jl/pull/277/commits/9b91dffa6d8a97f41581b9ed62b9bbc4f0e8dba4)

PR should be ready for merge

**Review by quinnj — APPROVED** [review]
Thanks @mathieu17g; I also pushed a fix for the nightly test failure, so I'll run the CI here again just to be careful.

**Pull request merged**
